'use client';
import { Geist, Geist_Mono } from 'next/font/google'
import { useEffect } from 'react';
import './globals.css'
import Header from '@/components/Header/Header'

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
})

const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  useEffect(() => {
	const handleSpace = (e) => {
	  if (e.code === 'Space' && document.activeElement === document.body) {
		e.preventDefault(); // empêche le scroll
	  }
	};

	window.addEventListener('keydown', handleSpace);
	return () => {
	  window.removeEventListener('keydown', handleSpace);
	};
  }, []);

	return (
		<html lang='fr'>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<Header />
				{children}
			</body>
		</html>
	)
}
